import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import { DiseaseAnalysis, SoilAnalysis } from '@/types';
import { formatDateTime, getHealthStatusColor, getFertilityLevelColor } from './utils';

type ReportType = "all" | "disease" | "soil";
type Report = (DiseaseAnalysis | SoilAnalysis) & { type: "disease" | "soil" };

export class ExportService {
  /**
   * Export reports to PDF
   */
  static exportToPDF(reports: Report[], filter: ReportType, searchTerm: string) {
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(20);
    doc.text('AgriAI Analysis Reports', 20, 20);
    
    // Add subtitle with filter info
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    const filterText = filter === 'all' ? 'All Reports' : `${filter.charAt(0).toUpperCase() + filter.slice(1)} Analysis`;
    doc.text(filterText, 20, 30);
    
    if (searchTerm) {
      doc.text(`Search: "${searchTerm}"`, 20, 37);
    }
    
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 44);
    
    // Prepare data for table
    const tableData = reports.map((report) => {
      if (report.type === 'disease') {
        const diseaseReport = report as DiseaseAnalysis;
        return [
          'Disease Analysis',
          diseaseReport.cropType || 'Not specified',
          diseaseReport.healthStatus.replace('_', ' ').toUpperCase(),
          `${diseaseReport.confidence}%`,
          `${diseaseReport.diseases.length + diseaseReport.pests.length} issues`,
          formatDateTime(diseaseReport.createdAt),
          diseaseReport.additionalNotes ? diseaseReport.additionalNotes.substring(0, 50) + '...' : 'No notes'
        ];
      } else {
        const soilReport = report as SoilAnalysis;
        return [
          'Soil Analysis',
          soilReport.soilType,
          soilReport.fertilityLevel.toUpperCase(),
          `${soilReport.confidence}%`,
          `${soilReport.issues.length} issues`,
          formatDateTime(soilReport.createdAt),
          soilReport.additionalNotes ? soilReport.additionalNotes.substring(0, 50) + '...' : 'No notes'
        ];
      }
    });
    
    // Add table
    autoTable(doc, {
      head: [['Type', 'Details', 'Status', 'Confidence', 'Issues', 'Date', 'Notes']],
      body: tableData,
      startY: 55,
      styles: {
        fontSize: 8,
        cellPadding: 2,
      },
      headStyles: {
        fillColor: [76, 175, 80], // Green color matching AgriAI theme
        textColor: 255,
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      columnStyles: {
        0: { cellWidth: 30 },
        1: { cellWidth: 25 },
        2: { cellWidth: 25 },
        3: { cellWidth: 20 },
        4: { cellWidth: 20 },
        5: { cellWidth: 25 },
        6: { cellWidth: 35 },
      },
    });
    
    // Add summary
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Reports: ${reports.length}`, 20, finalY);
    
    // Add footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by AgriAI - Agricultural Intelligence Platform', 20, doc.internal.pageSize.height - 10);
    
    // Save the PDF
    const fileName = `agriai-reports-${filter}-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  }
  
  /**
   * Export reports to Excel
   */
  static exportToExcel(reports: Report[], filter: ReportType, searchTerm: string) {
    // Create workbook
    const wb = XLSX.utils.book_new();
    
    // Prepare data for main sheet
    const mainData = reports.map((report) => {
      if (report.type === 'disease') {
        const diseaseReport = report as DiseaseAnalysis;
        return {
          'Report Type': 'Disease Analysis',
          'Crop Type': diseaseReport.cropType || 'Not specified',
          'Health Status': diseaseReport.healthStatus.replace('_', ' ').toUpperCase(),
          'Confidence': `${diseaseReport.confidence}%`,
          'Diseases Detected': diseaseReport.diseases.length,
          'Pests Detected': diseaseReport.pests.length,
          'Total Issues': diseaseReport.diseases.length + diseaseReport.pests.length,
          'Analysis Date': formatDateTime(diseaseReport.createdAt),
          'Additional Notes': diseaseReport.additionalNotes || 'No notes',
          'Image URL': diseaseReport.imageUrl || 'No image',
          'Location': diseaseReport.location ? 
            `${diseaseReport.location.city || ''} ${diseaseReport.location.state || ''} ${diseaseReport.location.country || ''}`.trim() : 
            'No location'
        };
      } else {
        const soilReport = report as SoilAnalysis;
        return {
          'Report Type': 'Soil Analysis',
          'Soil Type': soilReport.soilType,
          'Fertility Level': soilReport.fertilityLevel.toUpperCase(),
          'Confidence': `${soilReport.confidence}%`,
          'Issues Found': soilReport.issues.length,
          'Suitable Crops': soilReport.suitableCrops.length,
          'Analysis Date': formatDateTime(soilReport.createdAt),
          'Additional Notes': soilReport.additionalNotes || 'No notes',
          'Image URL': soilReport.imageUrl || 'No image',
          'Location': soilReport.location ? 
            `${soilReport.location.city || ''} ${soilReport.location.state || ''} ${soilReport.location.country || ''}`.trim() : 
            'No location'
        };
      }
    });
    
    // Create main sheet
    const mainSheet = XLSX.utils.json_to_sheet(mainData);
    XLSX.utils.book_append_sheet(wb, mainSheet, 'Reports');
    
    // Create detailed disease analysis sheet if there are disease reports
    const diseaseReports = reports.filter(r => r.type === 'disease') as DiseaseAnalysis[];
    if (diseaseReports.length > 0) {
      const diseaseData = diseaseReports.flatMap((report) => {
        const baseData = {
          'Report ID': report.id,
          'Crop Type': report.cropType || 'Not specified',
          'Health Status': report.healthStatus.replace('_', ' ').toUpperCase(),
          'Confidence': `${report.confidence}%`,
          'Analysis Date': formatDateTime(report.createdAt),
          'Image URL': report.imageUrl || 'No image'
        };
        
        // Add disease details
        if (report.diseases.length > 0) {
          return report.diseases.map((disease) => ({
            ...baseData,
            'Issue Type': 'Disease',
            'Issue Name': disease.name,
            'Severity': disease.severity.toUpperCase(),
            'Confidence': `${disease.confidence}%`,
            'Description': disease.description,
            'Symptoms': disease.symptoms.join(', '),
            'Causes': disease.causes.join(', ')
          }));
        }
        
        // Add pest details
        if (report.pests.length > 0) {
          return report.pests.map((pest) => ({
            ...baseData,
            'Issue Type': 'Pest',
            'Issue Name': pest.name,
            'Severity': pest.severity.toUpperCase(),
            'Confidence': `${pest.confidence}%`,
            'Description': pest.description
          }));
        }
        
        // If no issues, return base data
        return [{
          ...baseData,
          'Issue Type': 'None',
          'Issue Name': 'Healthy',
          'Severity': 'N/A',
          'Confidence': 'N/A',
          'Description': 'No diseases or pests detected'
        }];
      });
      
      const diseaseSheet = XLSX.utils.json_to_sheet(diseaseData);
      XLSX.utils.book_append_sheet(wb, diseaseSheet, 'Disease Details');
    }
    
    // Create detailed soil analysis sheet if there are soil reports
    const soilReports = reports.filter(r => r.type === 'soil') as SoilAnalysis[];
    if (soilReports.length > 0) {
      const soilData = soilReports.flatMap((report) => {
        const baseData = {
          'Report ID': report.id,
          'Soil Type': report.soilType,
          'Fertility Level': report.fertilityLevel.toUpperCase(),
          'Confidence': `${report.confidence}%`,
          'Analysis Date': formatDateTime(report.createdAt),
          'Image URL': report.imageUrl || 'No image'
        };
        
        // Add soil composition details
        const compositionData = {
          ...baseData,
          'Organic Matter': report.composition.organicMatter.toUpperCase(),
          'Moisture': report.composition.moisture.toUpperCase(),
          'Texture': report.composition.texture.toUpperCase(),
          'Color': report.composition.color
        };
        
        // Add nutrient details
        const nutrientData = {
          ...baseData,
          'Nitrogen': report.nutrients.nitrogen.toUpperCase(),
          'Phosphorus': report.nutrients.phosphorus.toUpperCase(),
          'Potassium': report.nutrients.potassium.toUpperCase(),
          'pH Level': report.nutrients.ph.toUpperCase()
        };
        
        // Add issues details
        const issuesData = report.issues.map((issue) => ({
          ...baseData,
          'Issue Type': issue.type.toUpperCase(),
          'Issue Severity': issue.severity.toUpperCase(),
          'Issue Description': issue.description
        }));
        
        // Add suitable crops details
        const cropsData = report.suitableCrops.map((crop) => ({
          ...baseData,
          'Crop Name': crop.cropName,
          'Suitability': crop.suitability.toUpperCase(),
          'Reason': crop.reason
        }));
        
        return [compositionData, nutrientData, ...issuesData, ...cropsData];
      });
      
      const soilSheet = XLSX.utils.json_to_sheet(soilData);
      XLSX.utils.book_append_sheet(wb, soilSheet, 'Soil Details');
    }
    
    // Create summary sheet
    const summaryData = [
      { 'Metric': 'Total Reports', 'Value': reports.length },
      { 'Metric': 'Disease Reports', 'Value': reports.filter(r => r.type === 'disease').length },
      { 'Metric': 'Soil Reports', 'Value': reports.filter(r => r.type === 'soil').length },
      { 'Metric': 'Filter Applied', 'Value': filter === 'all' ? 'All Reports' : filter.charAt(0).toUpperCase() + filter.slice(1) },
      { 'Metric': 'Search Term', 'Value': searchTerm || 'None' },
      { 'Metric': 'Export Date', 'Value': new Date().toLocaleDateString() },
      { 'Metric': 'Export Time', 'Value': new Date().toLocaleTimeString() }
    ];
    
    const summarySheet = XLSX.utils.json_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');
    
    // Save the Excel file
    const fileName = `agriai-reports-${filter}-${new Date().toISOString().split('T')[0]}.xlsx`;
    const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    const blob = new Blob([wbout], { type: 'application/octet-stream' });
    saveAs(blob, fileName);
  }
  
  /**
   * Export reports to CSV
   */
  static exportToCSV(reports: Report[], filter: ReportType, searchTerm: string) {
    // Prepare data for CSV
    const csvData = reports.map((report) => {
      if (report.type === 'disease') {
        const diseaseReport = report as DiseaseAnalysis;
        return {
          'Report Type': 'Disease Analysis',
          'Crop Type': diseaseReport.cropType || 'Not specified',
          'Health Status': diseaseReport.healthStatus.replace('_', ' ').toUpperCase(),
          'Confidence': `${diseaseReport.confidence}%`,
          'Diseases Detected': diseaseReport.diseases.length,
          'Pests Detected': diseaseReport.pests.length,
          'Total Issues': diseaseReport.diseases.length + diseaseReport.pests.length,
          'Analysis Date': formatDateTime(diseaseReport.createdAt),
          'Additional Notes': diseaseReport.additionalNotes || 'No notes'
        };
      } else {
        const soilReport = report as SoilAnalysis;
        return {
          'Report Type': 'Soil Analysis',
          'Soil Type': soilReport.soilType,
          'Fertility Level': soilReport.fertilityLevel.toUpperCase(),
          'Confidence': `${soilReport.confidence}%`,
          'Issues Found': soilReport.issues.length,
          'Suitable Crops': soilReport.suitableCrops.length,
          'Analysis Date': formatDateTime(soilReport.createdAt),
          'Additional Notes': soilReport.additionalNotes || 'No notes'
        };
      }
    });
    
    // Convert to CSV
    const headers = Object.keys(csvData[0]);
    const csvContent = [
      headers.join(','),
      ...csvData.map(row => 
        headers.map(header => {
          const value = row[header as keyof typeof row];
          // Escape commas and quotes in CSV
          if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
            return `"${value.replace(/"/g, '""')}"`;
          }
          return value;
        }).join(',')
      )
    ].join('\n');
    
    // Create and download CSV file
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const fileName = `agriai-reports-${filter}-${new Date().toISOString().split('T')[0]}.csv`;
    saveAs(blob, fileName);
  }
  
  /**
   * Export single report to PDF with beautiful design
   */
  static exportSingleReportToPDF(report: Report) {
    const doc = new jsPDF();
    
    // Set page dimensions and margins
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    const margin = 25;
    const contentWidth = pageWidth - (margin * 2);
    
    // Add beautiful header with gradient effect
    this.addBeautifulHeader(doc, report, pageWidth, margin);
    
    // Add report content
    let currentY = 80;
    
    if (report.type === 'disease') {
      currentY = this.addDiseaseReportContent(doc, report as DiseaseAnalysis, margin, currentY, contentWidth);
    } else {
      currentY = this.addSoilReportContent(doc, report as SoilAnalysis, margin, currentY, contentWidth);
    }
    
    // Add footer
    this.addBeautifulFooter(doc, pageWidth, pageHeight, margin);
    
    // Save the PDF
    const fileName = `agriai-${report.type}-report-${report.id || 'unknown'}-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  }
  
  /**
   * Export single report to Excel
   */
  static exportSingleReportToExcel(report: Report) {
    // Create workbook
    const wb = XLSX.utils.book_new();
    
    if (report.type === 'disease') {
      this.addDiseaseReportToExcel(wb, report as DiseaseAnalysis);
    } else {
      this.addSoilReportToExcel(wb, report as SoilAnalysis);
    }
    
    // Save the Excel file
    const fileName = `agriai-${report.type}-report-${report.id}-${new Date().toISOString().split('T')[0]}.xlsx`;
    const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    const blob = new Blob([wbout], { type: 'application/octet-stream' });
    saveAs(blob, fileName);
  }
  
  /**
   * Export single report to CSV
   */
  static exportSingleReportToCSV(report: Report) {
    let csvData;
    
    if (report.type === 'disease') {
      csvData = this.formatDiseaseReportForCSV(report as DiseaseAnalysis);
    } else {
      csvData = this.formatSoilReportForCSV(report as SoilAnalysis);
    }
    
    // Convert to CSV
    const headers = Object.keys(csvData[0]);
    const csvContent = [
      headers.join(','),
      ...csvData.map(row => 
        headers.map(header => {
          const value = row[header as keyof typeof row];
          if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
            return `"${value.replace(/"/g, '""')}"`;
          }
          return value;
        }).join(',')
      )
    ].join('\n');
    
    // Create and download CSV file
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const fileName = `agriai-${report.type}-report-${report.id}-${new Date().toISOString().split('T')[0]}.csv`;
    saveAs(blob, fileName);
  }
  
  /**
   * Add beautiful header to PDF
   */
  private static addBeautifulHeader(doc: jsPDF, report: Report, pageWidth: number, margin: number) {
    // Background rectangle with gradient effect
    doc.setFillColor(76, 175, 80); // Green
    doc.rect(0, 0, pageWidth, 60, 'F');
    
    // Add a subtle pattern overlay
    doc.setFillColor(255, 255, 255);
    for (let i = 0; i < pageWidth; i += 20) {
      doc.rect(i, 0, 10, 60, 'F');
    }
    
    // Logo/Icon placeholder with better positioning
    doc.setFillColor(255, 255, 255);
    doc.circle(margin + 20, 30, 18, 'F');
    doc.setTextColor(76, 175, 80);
    doc.setFontSize(24);
    doc.text('🌱', margin + 20, 36);
    
    // Title with better typography
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(26);
    doc.setFont('helvetica', 'bold');
    doc.text('AgriAI Analysis Report', margin + 50, 30);
    
    // Subtitle
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(`${report.type.charAt(0).toUpperCase() + report.type.slice(1)} Analysis`, margin + 50, 45);
    
    // Report metadata with better layout
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`Report ID: ${report.id || 'Unknown'}`, pageWidth - margin - 80, 25);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - margin - 80, 35);
    doc.text(`Confidence: ${report.confidence}%`, pageWidth - margin - 80, 45);
  }
  
  /**
   * Add disease report content to PDF
   */
  private static addDiseaseReportContent(doc: jsPDF, report: DiseaseAnalysis, margin: number, startY: number, contentWidth: number): number {
    let currentY = startY;
    
    // Section header
    currentY = this.addSectionHeader(doc, 'Crop Analysis Summary', margin, currentY);
    
    // Basic info table with better spacing
    const basicInfo = [
      ['Crop Type', report.cropType || 'Not specified'],
      ['Health Status', report.healthStatus.replace('_', ' ').toUpperCase()],
      ['Analysis Date', formatDateTime(report.createdAt)],
      ['Confidence Score', `${report.confidence}%`],
      ['Total Issues', `${report.diseases.length + report.pests.length}`]
    ];
    
    currentY = this.addStyledTable(doc, basicInfo, margin, currentY, contentWidth);
    
    // Detailed Diseases Section
    if (report.diseases.length > 0) {
      currentY = this.addSectionHeader(doc, 'Detected Diseases', margin, currentY + 15);
      
      report.diseases.forEach((disease, index) => {
        // Disease header with severity indicator
        doc.setTextColor(220, 38, 38); // Red for diseases
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${disease.name}`, margin, currentY);
        currentY += 8;
        
        // Disease details
        doc.setTextColor(75, 85, 99);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        
        // Severity and confidence
        doc.text(`Severity: ${disease.severity?.toUpperCase() || 'UNKNOWN'} | Confidence: ${disease.confidence || 0}%`, margin + 5, currentY);
        currentY += 6;
        
        // Description
        if (disease.description) {
          doc.text(`Description: ${disease.description}`, margin + 5, currentY, { maxWidth: contentWidth - 10 });
          currentY += 8;
        }
        
        // Symptoms
        if (disease.symptoms && disease.symptoms.length > 0) {
          doc.text('Symptoms:', margin + 5, currentY);
          currentY += 5;
          disease.symptoms.forEach(symptom => {
            doc.text(`• ${symptom}`, margin + 15, currentY, { maxWidth: contentWidth - 20 });
            currentY += 5;
          });
          currentY += 3;
        }
        
        // Causes
        if (disease.causes && disease.causes.length > 0) {
          doc.text('Causes:', margin + 5, currentY);
          currentY += 5;
          disease.causes.forEach(cause => {
            doc.text(`• ${cause}`, margin + 15, currentY, { maxWidth: contentWidth - 20 });
            currentY += 5;
          });
          currentY += 3;
        }
        
        currentY += 5; // Space between diseases
      });
    }
    
    // Detailed Pests Section
    if (report.pests.length > 0) {
      currentY = this.addSectionHeader(doc, 'Detected Pests', margin, currentY + 10);
      
      report.pests.forEach((pest, index) => {
        // Pest header with severity indicator
        doc.setTextColor(245, 158, 11); // Orange for pests
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${pest.name}`, margin, currentY);
        currentY += 8;
        
        // Pest details
        doc.setTextColor(75, 85, 99);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        
        // Severity and confidence
        doc.text(`Severity: ${pest.severity?.toUpperCase() || 'UNKNOWN'} | Confidence: ${pest.confidence || 0}%`, margin + 5, currentY);
        currentY += 6;
        
        // Description
        if (pest.description) {
          doc.text(`Description: ${pest.description}`, margin + 5, currentY, { maxWidth: contentWidth - 10 });
          currentY += 8;
        }
        
        currentY += 5; // Space between pests
      });
    }
    
    // Recommendations Section
    if (report.recommendations && report.recommendations.length > 0) {
      currentY = this.addSectionHeader(doc, 'Treatment Recommendations', margin, currentY + 10);
      
      report.recommendations.forEach((rec, index) => {
        // Recommendation header
        doc.setTextColor(59, 130, 246); // Blue for recommendations
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${rec.type.replace('_', ' ').toUpperCase()}`, margin, currentY);
        currentY += 6;
        
        // Recommendation details
        doc.setTextColor(75, 85, 99);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        
        // Action
        doc.text(`Action: ${rec.action}`, margin + 5, currentY, { maxWidth: contentWidth - 10 });
        currentY += 6;
        
        // Priority and timeframe
        doc.text(`Priority: ${rec.priority?.toUpperCase() || 'UNKNOWN'} | Timeframe: ${rec.timeframe?.replace('_', ' ') || 'UNKNOWN'}`, margin + 5, currentY);
        currentY += 8;
      });
    }
    
    // Additional notes
    if (report.additionalNotes) {
      currentY = this.addSectionHeader(doc, 'Additional Notes', margin, currentY + 10);
      doc.setTextColor(75, 85, 99);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text(report.additionalNotes, margin, currentY, { maxWidth: contentWidth });
      currentY += 20;
    }
    
    return currentY;
  }
  
  /**
   * Add soil report content to PDF
   */
  private static addSoilReportContent(doc: jsPDF, report: SoilAnalysis, margin: number, startY: number, contentWidth: number): number {
    let currentY = startY;
    
    // Section header
    currentY = this.addSectionHeader(doc, 'Soil Analysis Summary', margin, currentY);
    
    // Basic info table with better spacing
    const basicInfo = [
      ['Soil Type', report.soilType],
      ['Fertility Level', report.fertilityLevel.toUpperCase()],
      ['Analysis Date', formatDateTime(report.createdAt)],
      ['Confidence Score', `${report.confidence}%`],
      ['Total Issues', `${report.issues.length}`]
    ];
    
    currentY = this.addStyledTable(doc, basicInfo, margin, currentY, contentWidth);
    
    // Composition section
    currentY = this.addSectionHeader(doc, 'Soil Composition', margin, currentY + 15);
    const compositionData = [
      ['Property', 'Value'],
      ['Organic Matter', report.composition.organicMatter.toUpperCase()],
      ['Moisture', report.composition.moisture.toUpperCase()],
      ['Texture', report.composition.texture.toUpperCase()],
      ['Color', report.composition.color]
    ];
    currentY = this.addStyledTable(doc, compositionData, margin, currentY, contentWidth);
    
    // Nutrients section
    currentY = this.addSectionHeader(doc, 'Nutrient Levels', margin, currentY + 15);
    const nutrientData = [
      ['Nutrient', 'Level'],
      ['Nitrogen', report.nutrients.nitrogen.toUpperCase()],
      ['Phosphorus', report.nutrients.phosphorus.toUpperCase()],
      ['Potassium', report.nutrients.potassium.toUpperCase()],
      ['pH Level', report.nutrients.ph.toUpperCase()]
    ];
    currentY = this.addStyledTable(doc, nutrientData, margin, currentY, contentWidth);
    
    // Issues section with detailed information
    if (report.issues.length > 0) {
      currentY = this.addSectionHeader(doc, 'Soil Issues', margin, currentY + 15);
      
      report.issues.forEach((issue, index) => {
        // Issue header
        doc.setTextColor(220, 38, 38); // Red for issues
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${issue.type?.toUpperCase() || 'UNKNOWN'}`, margin, currentY);
        currentY += 8;
        
        // Issue details
        doc.setTextColor(75, 85, 99);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        
        // Severity
        doc.text(`Severity: ${issue.severity?.toUpperCase() || 'UNKNOWN'}`, margin + 5, currentY);
        currentY += 6;
        
        // Description
        if (issue.description) {
          doc.text(`Description: ${issue.description}`, margin + 5, currentY, { maxWidth: contentWidth - 10 });
          currentY += 8;
        }
        
        currentY += 5; // Space between issues
      });
    }
    
    // Suitable crops section with detailed information
    if (report.suitableCrops.length > 0) {
      currentY = this.addSectionHeader(doc, 'Suitable Crops', margin, currentY + 15);
      
      report.suitableCrops.forEach((crop, index) => {
        // Crop header
        doc.setTextColor(34, 197, 94); // Green for suitable crops
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${crop.cropName || 'Unknown'}`, margin, currentY);
        currentY += 8;
        
        // Crop details
        doc.setTextColor(75, 85, 99);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        
        // Suitability
        doc.text(`Suitability: ${crop.suitability?.toUpperCase() || 'UNKNOWN'}`, margin + 5, currentY);
        currentY += 6;
        
        // Reason
        if (crop.reason) {
          doc.text(`Reason: ${crop.reason}`, margin + 5, currentY, { maxWidth: contentWidth - 10 });
          currentY += 8;
        }
        
        currentY += 5; // Space between crops
      });
    }
    
    // Recommendations section
    if (report.recommendations && report.recommendations.length > 0) {
      currentY = this.addSectionHeader(doc, 'Improvement Recommendations', margin, currentY + 15);
      
      report.recommendations.forEach((rec, index) => {
        // Recommendation header
        doc.setTextColor(59, 130, 246); // Blue for recommendations
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text(`${index + 1}. ${rec.type?.toUpperCase() || 'UNKNOWN'}`, margin, currentY);
        currentY += 6;
        
        // Recommendation details
        doc.setTextColor(75, 85, 99);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        
        // Action
        doc.text(`Action: ${rec.action}`, margin + 5, currentY, { maxWidth: contentWidth - 10 });
        currentY += 6;
        
        // Priority and expected improvement
        doc.text(`Priority: ${rec.priority?.toUpperCase() || 'UNKNOWN'} | Expected Improvement: ${rec.expectedImprovement || 'Not specified'}`, margin + 5, currentY);
        currentY += 8;
      });
    }
    
    // Additional notes
    if (report.additionalNotes) {
      currentY = this.addSectionHeader(doc, 'Additional Notes', margin, currentY + 15);
      doc.setTextColor(75, 85, 99);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text(report.additionalNotes, margin, currentY, { maxWidth: contentWidth });
      currentY += 20;
    }
    
    return currentY;
  }
  
  /**
   * Add section header to PDF
   */
  private static addSectionHeader(doc: jsPDF, title: string, margin: number, y: number): number {
    // Add subtle background for section headers
    doc.setFillColor(248, 250, 252);
    doc.rect(margin - 5, y - 8, 200, 25, 'F');
    
    // Add colored accent line
    doc.setFillColor(76, 175, 80);
    doc.rect(margin - 5, y - 8, 4, 25, 'F');
    
    // Section title
    doc.setTextColor(31, 41, 55);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, y);
    
    return y + 20;
  }
  
  /**
   * Add styled table to PDF
   */
  private static addStyledTable(doc: jsPDF, data: string[][], margin: number, startY: number, contentWidth: number): number {
    autoTable(doc, {
      head: [data[0]],
      body: data.slice(1),
      startY: startY,
      styles: {
        fontSize: 11,
        cellPadding: 6,
        lineWidth: 0.5,
        lineColor: [229, 231, 235],
      },
      headStyles: {
        fillColor: [76, 175, 80],
        textColor: 255,
        fontStyle: 'bold',
        fontSize: 12,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      columnStyles: {
        0: { cellWidth: contentWidth * 0.35, fontStyle: 'bold' },
        1: { cellWidth: contentWidth * 0.65 },
      },
      margin: { left: margin, right: margin },
      tableWidth: contentWidth,
      didDrawPage: function (data) {
        // Add subtle border around table
        doc.setDrawColor(229, 231, 235);
        doc.setLineWidth(1);
        doc.rect(margin - 2, startY - 2, contentWidth + 4, (data as any).table.height + 4, 'S');
      }
    });
    
    return (doc as any).lastAutoTable.finalY + 15;
  }
  
  /**
   * Add beautiful footer to PDF
   */
  private static addBeautifulFooter(doc: jsPDF, pageWidth: number, pageHeight: number, margin: number) {
    // Footer background with gradient effect
    doc.setFillColor(76, 175, 80);
    doc.rect(0, pageHeight - 35, pageWidth, 35, 'F');
    
    // Add subtle pattern to footer
    doc.setFillColor(255, 255, 255);
    for (let i = 0; i < pageWidth; i += 15) {
      doc.rect(i, pageHeight - 35, 8, 35, 'F');
    }
    
    // Footer text with better positioning
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Generated by AgriAI - Agricultural Intelligence Platform', margin, pageHeight - 20);
    doc.text('Empowering farmers with AI-driven insights', pageWidth - margin - 140, pageHeight - 20);
    
    // Add version and timestamp
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`v1.0 | ${new Date().toLocaleString()}`, pageWidth - margin - 80, pageHeight - 10);
  }
  
  /**
   * Add disease report to Excel workbook
   */
  private static addDiseaseReportToExcel(wb: any, report: DiseaseAnalysis) {
    // Main summary sheet
    const summaryData = [
      { 'Field': 'Report Type', 'Value': 'Disease Analysis' },
      { 'Field': 'Crop Type', 'Value': report.cropType || 'Not specified' },
      { 'Field': 'Health Status', 'Value': report.healthStatus.replace('_', ' ').toUpperCase() },
      { 'Field': 'Confidence', 'Value': `${report.confidence}%` },
      { 'Field': 'Analysis Date', 'Value': formatDateTime(report.createdAt) },
      { 'Field': 'Total Issues', 'Value': report.diseases.length + report.pests.length }
    ];
    
    const summarySheet = XLSX.utils.json_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');
    
    // Diseases sheet
    if (report.diseases.length > 0) {
      const diseaseData = report.diseases.map(d => ({
        'Issue Type': 'Disease',
        'Name': d.name,
        'Severity': d.severity.toUpperCase(),
        'Confidence': `${d.confidence}%`,
        'Description': d.description,
        'Symptoms': d.symptoms.join(', '),
        'Causes': d.causes.join(', ')
      }));
      
      const diseaseSheet = XLSX.utils.json_to_sheet(diseaseData);
      XLSX.utils.book_append_sheet(wb, diseaseSheet, 'Diseases');
    }
    
    // Pests sheet
    if (report.pests.length > 0) {
      const pestData = report.pests.map(p => ({
        'Issue Type': 'Pest',
        'Name': p.name,
        'Severity': p.severity.toUpperCase(),
        'Confidence': `${p.confidence}%`,
        'Description': p.description
      }));
      
      const pestSheet = XLSX.utils.json_to_sheet(pestData);
      XLSX.utils.book_append_sheet(wb, pestSheet, 'Pests');
    }
  }
  
  /**
   * Add soil report to Excel workbook
   */
  private static addSoilReportToExcel(wb: any, report: SoilAnalysis) {
    // Main summary sheet
    const summaryData = [
      { 'Field': 'Report Type', 'Value': 'Soil Analysis' },
      { 'Field': 'Soil Type', 'Value': report.soilType },
      { 'Field': 'Fertility Level', 'Value': report.fertilityLevel.toUpperCase() },
      { 'Field': 'Confidence', 'Value': `${report.confidence}%` },
      { 'Field': 'Analysis Date', 'Value': formatDateTime(report.createdAt) }
    ];
    
    const summarySheet = XLSX.utils.json_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');
    
    // Composition sheet
    const compositionData = [
      { 'Property': 'Organic Matter', 'Value': report.composition.organicMatter.toUpperCase() },
      { 'Property': 'Moisture', 'Value': report.composition.moisture.toUpperCase() },
      { 'Property': 'Texture', 'Value': report.composition.texture.toUpperCase() },
      { 'Property': 'Color', 'Value': report.composition.color }
    ];
    
    const compositionSheet = XLSX.utils.json_to_sheet(compositionData);
    XLSX.utils.book_append_sheet(wb, compositionSheet, 'Composition');
    
    // Nutrients sheet
    const nutrientData = [
      { 'Nutrient': 'Nitrogen', 'Level': report.nutrients.nitrogen.toUpperCase() },
      { 'Nutrient': 'Phosphorus', 'Level': report.nutrients.phosphorus.toUpperCase() },
      { 'Nutrient': 'Potassium', 'Level': report.nutrients.potassium.toUpperCase() },
      { 'Nutrient': 'pH Level', 'Level': report.nutrients.ph.toUpperCase() }
    ];
    
    const nutrientSheet = XLSX.utils.json_to_sheet(nutrientData);
    XLSX.utils.book_append_sheet(wb, nutrientSheet, 'Nutrients');
    
    // Issues sheet
    if (report.issues.length > 0) {
      const issuesData = report.issues.map(i => ({
        'Issue Type': i.type.toUpperCase(),
        'Severity': i.severity.toUpperCase(),
        'Description': i.description
      }));
      
      const issuesSheet = XLSX.utils.json_to_sheet(issuesData);
      XLSX.utils.book_append_sheet(wb, issuesSheet, 'Issues');
    }
    
    // Suitable crops sheet
    if (report.suitableCrops.length > 0) {
      const cropsData = report.suitableCrops.map(c => ({
        'Crop Name': c.cropName,
        'Suitability': c.suitability.toUpperCase(),
        'Reason': c.reason
      }));
      
      const cropsSheet = XLSX.utils.json_to_sheet(cropsData);
      XLSX.utils.book_append_sheet(wb, cropsSheet, 'Suitable Crops');
    }
  }
  
  /**
   * Format disease report for CSV
   */
  private static formatDiseaseReportForCSV(report: DiseaseAnalysis) {
    const baseData = {
      'Report Type': 'Disease Analysis',
      'Crop Type': report.cropType || 'Not specified',
      'Health Status': report.healthStatus.replace('_', ' ').toUpperCase(),
      'Confidence': `${report.confidence}%`,
      'Analysis Date': formatDateTime(report.createdAt)
    };
    
    if (report.diseases.length > 0) {
      return report.diseases.map(d => ({
        ...baseData,
        'Issue Type': 'Disease',
        'Issue Name': d.name,
        'Severity': d.severity.toUpperCase(),
        'Issue Confidence': `${d.confidence}%`,
        'Description': d.description
      }));
    } else if (report.pests.length > 0) {
      return report.pests.map(p => ({
        ...baseData,
        'Issue Type': 'Pest',
        'Issue Name': p.name,
        'Severity': p.severity.toUpperCase(),
        'Issue Confidence': `${p.confidence}%`,
        'Description': p.description
      }));
    } else {
      return [{
        ...baseData,
        'Issue Type': 'None',
        'Issue Name': 'Healthy',
        'Severity': 'N/A',
        'Issue Confidence': 'N/A',
        'Description': 'No issues detected'
      }];
    }
  }
  
  /**
   * Format soil report for CSV
   */
  private static formatSoilReportForCSV(report: SoilAnalysis) {
    const baseData = {
      'Report Type': 'Soil Analysis',
      'Soil Type': report.soilType,
      'Fertility Level': report.fertilityLevel.toUpperCase(),
      'Confidence': `${report.confidence}%`,
      'Analysis Date': formatDateTime(report.createdAt)
    };
    
    return [
      { ...baseData, 'Property': 'Organic Matter', 'Value': report.composition.organicMatter.toUpperCase() },
      { ...baseData, 'Property': 'Moisture', 'Value': report.composition.moisture.toUpperCase() },
      { ...baseData, 'Property': 'Texture', 'Value': report.composition.texture.toUpperCase() },
      { ...baseData, 'Property': 'Color', 'Value': report.composition.color },
      { ...baseData, 'Property': 'Nitrogen', 'Value': report.nutrients.nitrogen.toUpperCase() },
      { ...baseData, 'Property': 'Phosphorus', 'Value': report.nutrients.phosphorus.toUpperCase() },
      { ...baseData, 'Property': 'Potassium', 'Value': report.nutrients.potassium.toUpperCase() },
      { ...baseData, 'Property': 'pH Level', 'Value': report.nutrients.ph.toUpperCase() }
    ];
  }
  
  /**
   * Get export options based on available data
   */
  static getExportOptions(reports: Report[], filter: ReportType) {
    const options = [
      { id: 'pdf', label: 'Export to PDF', icon: '📄', description: 'Professional PDF report with tables and formatting' },
      { id: 'excel', label: 'Export to Excel', icon: '📊', description: 'Multi-sheet Excel file with detailed data' }
    ];
    
    // Add CSV option for simple data export
    if (reports.length > 0) {
      options.push({ 
        id: 'csv', 
        label: 'Export to CSV', 
        icon: '📋', 
        description: 'Simple CSV file for spreadsheet applications' 
      });
    }
    
    return options;
  }
  
  /**
   * Get single report export options
   */
  static getSingleReportExportOptions() {
    return [
      { id: 'pdf', label: 'Export to PDF', icon: '📄', description: 'Beautiful PDF report with modern design' },
      { id: 'excel', label: 'Export to Excel', icon: '📊', description: 'Detailed Excel workbook with multiple sheets' },
      { id: 'csv', label: 'Export to CSV', icon: '📋', description: 'Simple CSV format for data analysis' }
    ];
  }
}
